### PR TITLE
Fix passing reference

### PR DESCRIPTION
**Pull request by eigmax**

### CODE REVIEW

**Comment by rachel-bousfield** [comment]
Adding a leading `&` doesn't change the hash, and we want to move the value. Thanks for the PR though!

**Comment by eigmax** [comment]
Why should we move?  it's deconstructed after the block is executed automatically.  What's your rust version?    I use rustc 1.53.0-nightly and get error: 

image

**Comment by eigmax** [comment]
@RachelFranks

**Comment by rachel-bousfield** [comment]
Your rust is out of date, please update to the latest release

**Pull request closed without merging**
